### ISSUE TITLE
pia rejected cannot be edited

### ISSUE THREAD

**Issue by bea568** [LINCnil/pia-app#11]
When I reject a pia, even if I click on "Edit pia", I have no possibility to edit fields, except to add "Comment". I am blocked with a rejected pia, so I duplicated my rejected pia and now I can edit it. Is there another alternative ?

**Comment by LaboCNIL** [comment]
When rejecting a PIA, it is sent back to its evaluation state. You can either edit the evaluations made (eg. adding additional measures to protect the data) or send the PIA back to its edition state by selecting a "To correct" evaluation in the section you wish to edit.

**Comment by bea568** [comment]
I cannot add additional measures or click on "To correct". I can only leave a comment by clicking on "Comment" or add an attached file.
