### ISSUE TITLE
colors of the risk mapping

### ISSUE THREAD

**Issue by bea568** [LINCnil/pia-app#12]
The risk mapping should be similar as the one in the "Modèles et bases de connaissances" publied by CNIL, on page 22. There are 4 colours and 4 squares.

**Comment by LaboCNIL** [comment]
The risk mapping is similar to the one published in the CNIL method.

**Comment by bea568** [comment]
In the CNIL method, the risk mapping is like this : 
![risk mapping_cnil method](https://user-images.githubusercontent.com/34300604/34160048-b2bf5b8e-e4cb-11e7-891d-ddef6005eb1e.PNG)

and in the pia tool, the risk mapping is like this : 
![risk mapping_pia tool](https://user-images.githubusercontent.com/34300604/34160060-bcaf0504-e4cb-11e7-91eb-27e691e0bae1.PNG)
