### ISSUE TITLE
Question générale sur PIA

### ISSUE THREAD

**Issue by CCoruble** [LINCnil/pia-app#17]
Bonjour,

Je souhaiterais savoir où sont stockés les pia, lorsque l'on utilise l'application portable en local, la langue par défaut lorsque l'on lance l'application et l'adresse du serveur.

Merci d'avance,
Cordialement.

**Comment by CCoruble** [comment]
Egalement, est-il possible de passer l'adresse du serveur en https au lieu de http ? Et envisagez-vous de mettre d'autre langues telle que l'anglais et l'allemand.

**Comment by LaboCNIL** [comment]
Bonjour,

Lors de l'utilisation de l'application portable en local, les pias sont stockés dans les répertoires suivants :
- Windows : _"C:\Users\Username\AppData\Roaming\PIA"_
- Mac : _"/Users/username/Library/Application Support/PIA"_
- Linux : _"~/.config/$YOUR_APP_NAME"_

L'anglais est disponible dans le logiciel. L'allemand ne l'est pas encore.

**Comment by CCoruble** [comment]
Bonjour,
Merci d'avoir répondu à certaines des questions.
Pour les langues je voulais dire l'espagnol et l'allemand, mais je suppose que l'espagnol sera disponible plus tard au même titre que l'allemand.

Cordialement

**Comment by LaboCNIL** [comment]
Bonjour,

Nous invitons les membres de la communauté à proposer leur traduction dans les langues non disponibles. Si vous désirez faire cela, nous vous invitons à suivre le tutoriel suivant afin de nous soumettre vos traductions : https://github.com/LINCnil/pia/tree/master/src/assets/i18n

Cordialement,
