### ISSUE TITLE
Risk mapping

### ISSUE THREAD

**Issue by bea568** [LINCnil/pia-app#18]
In the CNIL method, the risk mapping is like this : 
![risk mapping_cnil method](https://user-images.githubusercontent.com/34300604/34160048-b2bf5b8e-e4cb-11e7-891d-ddef6005eb1e.PNG)

and in the pia tool, the risk mapping is like this : 
![risk mapping_pia tool](https://user-images.githubusercontent.com/34300604/34160060-bcaf0504-e4cb-11e7-91eb-27e691e0bae1.PNG)

**Comment by LaboCNIL** [comment]
Both charts are actually equivalent, the only difference is their appearance.
