### ISSUE TITLE
autocompletion in risks section

### ISSUE THREAD

**Issue by Dan33l** [LINCnil/pia-app#2]
It should be user friendly if the application is able to autocomplete impacts, threats and sources in subsections `illegitimate access to data`, `unwanted modification to data` and `data disappearance`, based on items already provided by user.

If i added  `damaging the reputation` as a risk in the sub section `illegitimate access to data`, it will be also possible to meet the same risk about `unwanted modification to data` and `data disappearance`. For the moment, i have to enter tree times this risk exactly in a same manner to permit an interesting risks overview section.

reported with version 1.1.6

**Comment by kevin-atnos** [comment]
Hello,

This feature has been developed and will be available for the next version.

Thank you.
