### ISSUE TITLE
PIA Risk display truncated

### ISSUE THREAD

**Issue by zoe2414** [LINCnil/pia-app#20]
Bonjour,
Lors de la visualisation ou l'export du PIA, le risque "Disparition de données" est tronqué - seul apparaît la première question (impact).  Ce problème se pose quelle que soit la langue choisie, et seulement pour ce troisième risque (les deux premiers s'affichent correctement, accompagnés de leurs 6 questions).

**Comment by brunto** [comment]
Bonjour,
Ce problème a été corrigé dans la future version 1.5 qui va sortir sous peu.
