### ISSUE TITLE
MacOS build Issue

### ISSUE THREAD

**Issue by loretoparisi** [LINCnil/pia-app#30]
I have done a new build and deployed the app on macOS 10.12:

```
npm install -g electron-builder
npm install
npm run mac
```

I have the dmg in the dist folder

But I see a white screen when starting up:

```
$ tree -L 1 -h
.
├── [ 45M]  PIA-1.6.2-mac.zip
├── [ 46M]  PIA-1.6.2.dmg
├── [ 51K]  PIA-1.6.2.dmg.blockmap
├── [ 446]  electron-builder.yaml
├── [ 102]  github
├── [ 454]  latest-mac.yml
└── [ 102]  mac
```
<img width="900" alt="schermata 2018-03-28 alle 19 31 51" src="https://user-images.githubusercontent.com/163333/38045988-b34ccbe0-32be-11e8-8df8-1fbb7342e9ae.png">

**Comment by loretoparisi** [comment]
any update on this?

**Comment by brunto** [comment]
Hello @loretoparisi sorry for the delay.
And with `npm start` do you see smtg?

**Comment by brunto** [comment]
Any news?

**Comment by loretoparisi** [comment]
@brunto thank you I will check this out asap.

**Comment by brunto** [comment]
You can also download the latest version 2.0 : https://github.com/LINCnil/pia-app/releases/download/2.0.0/PIA-2.0.0.dmg
