### ISSUE TITLE
PIA Examples of APPLICATION TO CONNECTED OBJECTS

### ISSUE THREAD

**Issue by loretoparisi** [LINCnil/pia-app#31]
Hello, it would be very worth to provide the `PRIVACY IMPACT ASSESSMENT (PIA) : APPLICATION TO CONNECTED OBJECTS` as a PIA import file, that one could load into the software as a tutorial.

**Comment by brunto** [comment]
You can now create a PIA based on the template "Example : PIAF Connected Objects" with the version 2 of the application.
