### ISSUE TITLE
visibilité des projets créés

### ISSUE THREAD

**Issue by segq9pc** [LINCnil/pia-app#33]
Bonjour,
Je viens de finaliser l'installation de Pia en back et en front.

Comment peut on rendre visible tout les projets créés? à l'ensemble des utlisateurs?
merci

**Comment by brunto** [comment]
Bonjour,
Il suffit pour cela de donner l'URL du serveur de production à tous vos utilisateurs : https://github.com/LINCnil/pia-back#run-the-application
