### ISSUE TITLE
error when npm run

### ISSUE THREAD

**Issue by ideiudicibus** [LINCnil/pia-app#34]
I've got this error issued after the npm install.
 
[error] Error: Error: ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\projects\pia-app\dev-app-update.yml'

node: 
v8.9.4
npm: 
5.6.0

am I missing some file?

**Comment by brunto** [comment]
Hello,
Could you try with the latest.

**Comment by brunto** [comment]
Any news?
