### ISSUE TITLE
Failed to create a new PIA

### ISSUE THREAD

**Issue by raffaeler** [LINCnil/pia-app#35]
I downloaded and installed the 1.60 on Windows.
When trying to create a new PIA, I filled all the fields (title, authors, reviewers, etc.) and the button gets enabled.
The problem is that clicking the enabled button does nothing.
What am I missing?
TIA

**Comment by brunto** [comment]
Hello,
It's strange, could you try with the 1.6.3 version? https://github.com/LINCnil/pia-app/releases/tag/1.6.3

**Comment by brunto** [comment]
Any news?

**Comment by raffaeler** [comment]
No way ... i just installed the release 1.6.3 and repeated the test.
![image](https://user-images.githubusercontent.com/5183152/50765320-d70df300-1275-11e9-93b7-2528e5905554.png)
When I press "Start" nothing happens.

BTW, when I first run the app, it tells me to press "+" ... but the "+" is not there. You maybe should start from the "card" view, where the "+" is available.
![image](https://user-images.githubusercontent.com/5183152/50765110-33244780-1275-11e9-9285-b997e7b8c2c1.png)

**Comment by brunto** [comment]
Could you remove the folder `C:\Users\Username\AppData\Roaming\PIA`
Then download the latest 2.0 version : https://github.com/LINCnil/pia-app/releases/download/2.0.0/PIA-Setup-2.0.0.exe
And try again?
