### ISSUE TITLE
Plan d'action - Mesures existantes ou prévues non définies (undefined)

### ISSUE THREAD

**Issue by Althior** [LINCnil/pia-app#36]
Bonjour,

J'ai un problème avec le plan d'action, la partie "Mesures existantes ou prévues" affiche les mesures qui ne sont pas définies (car déjà présentes). Par exemple : 
> Chiffrement
> undefined
> Date prévue de mise en œuvre 01/01/1970

Et ce pour chaque mesure de cette rubrique (à part pour les mesures effectivement prévues avec une date, responsable, ...).
J'utilise la dernière version (1.6.0) du logiciel PIA pour Windows.

Merci d'avance.

**Comment by brunto** [comment]
Bonjour,
Une nouvelle version va sortir très prochainement, cela va résoudre ce problème.
