### ISSUE TITLE
Comments : edit and delete

### ISSUE THREAD

**Issue by jgachelin** [LINCnil/pia-app#41]
Is it possible to add a functionality to edit/remove a comment under a description ?
The only way I know for now is to export the PIA in JSON, editing the JSON to edit or delete a comment, then import the PIA back to the software. This is not very user-friendly :)
Thanks for your work !

Note : PIA **v.1.6.3** and **v.2.0.0**

**Comment by kevin-atnos** [comment]
Hello,

Maybe it could change in the future, but the decision was made to not let users remove comments from questions/measures. This allows users to have a complete "history" of all discussions about a specific question/measure. 

But you are right, if some comments really bother you, manually updating the .json can be a great solution.
