### ISSUE TITLE
JSON export and attached document

### ISSUE THREAD

**Issue by jgachelin** [LINCnil/pia-app#42]
During a JSON export then import, if there is an attached document to the PIA, it disappear.
It would be nice to keep this document mentioned, not necessarily linked to the file, in order to know which document could complete the PIA.
Thanks.

Note : PIA **v.1.6.3** and **v.2.0.0**

**Comment by kevin-atnos** [comment]
Hello,

In the next version (PIA 2.2.0), you will be able to export your PIA (.json document) with all your  attachments, contained in a .zip folder. This will allow you to keep all your documents with your PIA in a specific folder.

This new version is coming very soon, stay tuned!

**Comment by SCozijnsen** [comment]
Thanks for the great addition! :D We use this in our workflow from creation to validation between the different responsible people.
But it looks like the attachments are not included in the json file. So after an export and import of the PIA the attachments are still not visible in the editor anymore. Also the attachment folder is localized and that might give problems with users with different language settings. It would be awesome if this could be also incorporated!

**Comment by kevin-atnos** [comment]
> Thanks for the great addition! :D We use this in our workflow from creation to validation between the different responsible people.
> But it looks like the attachments are not included in the json file. So after an export and import of the PIA the attachments are still not visible in the editor anymore. Also the attachment folder is localized and that might give problems with users with different language settings. It would be awesome if this could be also incorporated!

Hello,

Thank you for your feedback!

### General information
The attachments are joined with the .JSON file in a .zip folder.
If you want to import your .JSON file on another computer or if someone else wants to use it, you have to re-attach the different attachments in the newly imported PIA. Attachments are separated from the JSON file and we can't change that, so people need to manually add them after the import.

### Two ways to get your .JSON and attachments (+ other documents)

#### PIA homepage (Card/List)
You can get your .JSON (and your attachments if there are some), using the export button.
Example here in Card mode, with a PIA containing 2 attachments (you can see the special icon on the left):
![pia-5](https://user-images.githubusercontent.com/24872475/79967834-a4e6cb80-848f-11ea-8889-5c50a644b559.png)

After clicking this button, you should be able to download a zip containg your JSON and your attachments:

![pia-2](https://user-images.githubusercontent.com/24872475/79966807-466d1d80-848e-11ea-9f6b-b69de8dcc6ac.png)
![pia-3](https://user-images.githubusercontent.com/24872475/79966837-4e2cc200-848e-11ea-87f7-3930137a0c59.png)

#### PIA "Consult" page
You can also use the PIA consult page where you can export the .JSON and the attachments.
There are additional documents you can export from this page (visual elements, action plan, .doc, ...)

![pia-4](https://user-images.githubusercontent.com/24872475/79967464-2a1db080-848f-11ea-91af-db3a9fe0b706.png)

Thank you, do not hesite if you any other question.

**Comment by Fabienne-l** [comment]
Hello,
I have a similar problem: I cannot export a correct file JSON from PIA. I don't know which kind of file I upload but when I try to import it, nothing is happening in PIA. It is really problematic because I cannot exchange files with my colleagues. Thank you for your help.

PS: I use the last version (2.2.1)
Fabienne

**Comment by SCozijnsen** [comment]
@Fabienne-l : I had a similar error when the tool was installed on a network drive. The export function did not work correct then. Installing the PIA tool on the local machine solved this problem for me.

**Comment by SCozijnsen** [comment]
@kevin-atnos : 

>  Attachments are separated from the JSON file and we can't change that

What I meant was if it would be possible to inlcude the filepaths of the attachments in the json file so they can be automaticly connected at import. That would be technically possible right? 

Manually importing is not that bad but we have to deal with the users... ;-)

**Comment by Fabienne-l** [comment]
Thank you **SCozijnsen** for your very quick response. 

The PIA tool is installed directly on my computer. What it means  "install it "on the local machine"? 
However, the CNIL says regarding the "Portable Version", This version can be directly downloaded and launched on your computer **with no need to install it locally**.
I'm not sure I understood everything.

**Comment by SCozijnsen** [comment]
@Fabienne-l Well as far as I know, if you just run the installer from the download, The PIA does get extracted to you ProgramFiles folder. You could also choose to do this to any other folder on your computer, a network drive or a USB stick. So in that sense it does not really 'install' anything. But this goes beyond the topic of this threat.
