### ISSUE TITLE
Risk overview : print

### ISSUE THREAD

**Issue by jgachelin** [LINCnil/pia-app#43]
When I try to print a PIA, the display of links is completely broken.
The issue is the same using print function or using PDF Creator.
Here is an example : 
![logicielpia](https://user-images.githubusercontent.com/16141377/49653407-1ce85900-fa35-11e8-82b9-e39ccf1d83a1.png)
Thanks :)

Note : PIA **v.1.6.3** and **v.2.0.0**

**Comment by brunto** [comment]
Hello, could you give me your operating system name&version and your browser name&version?

**Comment by jgachelin** [comment]
Operating System : Windows 7
The issue is the same with : 
- Direct print on paper
- Export with PDFCreator and visualize the PDF on Adobe Reader (v11) or Firefox (v63)

No problem on the PIA software itself.
(This is not the web version of PIA, it's the PIA portable version)

**Comment by brunto** [comment]
We will add soon a button to export in pdf format.
See: https://github.com/LINCnil/pia-app/issues/4

**Comment by jgachelin** [comment]
The issue is different than #4 , here the problem is the render, with print function too.

**Comment by brunto** [comment]
I think this problem come from the browser (and/or operating system).

**Comment by jgachelin** [comment]
Printing (to a physical printer) is done directly from the PIA software. I don't think that is related to any web browser.
This case occurs on Windows 7.
