### ISSUE TITLE
Select a file on a deleting folder

### ISSUE THREAD

**Issue by jgachelin** [LINCnil/pia-app#44]
When I want to select a file from PIA software, it opens the last folder used in the software.
But if this folder don't exist anymore, it still works anyway because it's recreates the folder.

PIA version : 2.0.0
OS : Windows 7

Thanks :)

**Comment by brunto** [comment]
This is not due to the PIA application but comes from the Electron framework.
You can open an issue here if you want: https://github.com/electron/electron
