### ISSUE TITLE
Version portable - Création nouveau PIA impossible

### ISSUE THREAD

**Issue by quoidautre** [LINCnil/pia-app#54]
Bonjour,

Je viens de télécharger la version Windows, dernière release 2.1.0.

Lors de la création d'un nouveau PIA, après avoir saisi l'intitulé, le nom, etc, et avoir cliqué sur le bouton "commencer" (qui se met bien au vert), rien ne se passe. 
Le soft ne réagit pas, je n'ai aucun message d'erreur ; le PIA ne se créer donc pas.
Idem pour la création d'un modèle.

L'import d'un PIA ne fonctionne pas non plus, rien ne se passe.

Cela a été testé sur un autre poste sans succès, et en "mode administrateur", idem.

Merci.

F.

**Comment by brunto** [comment]
Bonjour,
Est-il possible de faire un partage d'écran ?

**Comment by ghost** [comment]
Bonjour,

Qu'entendez-vous par "partage d'écran" ?, une copie d'écran ?, un prise en main à distance ?

Désolé pour le retard de ma réponse, vacances oblige.

Merci
Fabrice

**Comment by brunto** [comment]
Soit une prise en main à distance, soit un partage d'écran avec conversation téléphonique.
