### ISSUE TITLE
Section a corriger - Impossible a ré évaluer

### ISSUE THREAD

**Issue by zobi** [LINCnil/pia-app#59]
J'obtiens un bug reproductible (je suis en 2.2.0) et je n'arrive pas à m'en sortir.
Je rempli en mode édition la section "Vue d'ensemble" 
J'envoie la demande d'évaluation
L'évaluateur note "A Corriger" et renvoie donc la partie en mode Edition.
De la impossible de revenir en mode évaluateur, je clique sur le bouton "Demande l'évaluation" j'ai le message "La partie est disponible pour évaluation" mais elle reste en mode Edition je ne peux plus choisir "Acceptable"  le section est définitivement bloqué en mode "A Corriger".

J'ai la même problématique pour toutes les sections ... 

Merci

**Comment by zobi** [comment]
J'ai essayé aussi sur la version web et même problème je suppose donc que le problème est sur le pia-back

**Comment by brunto** [comment]
Bonjour,
Est-ce possible de faire un partage d'écran afin que l'on puisse regarder l'origine du dysfonctionnement ?

**Comment by kevin-atnos** [comment]
@zobi Bonjour,

Avez-vous trouvé une solution à votre problème ?
Nous restons à votre disposition pour faire un partage d'écran ou autre.

Merci à vous.
