### ISSUE TITLE
Échec d’import: erreur liée à des caractères Unicode

### ISSUE THREAD

**Issue by tfaujour** [LINCnil/pia-app#60]
En version 2.2.0 sous Windows, j’ai exporté un PIA mais il était impossible de l’importer (rien ne se passe, pas de message d’erreur).

En essayant de lire le fichier JSON (`jq . pia.json`), j’ai obtenu l’erreur suivante:
```parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 310```

Il s’avère qu’il y avait des caractères non-échappés (en l’occurrence, des apostrophes typographiques (’)) dans:

- Le nom du PIA
- Les impacts, menaces et sources des risques

Je suggèrerais:

- D’échapper les caractères qui le nécessitent
- De donner accès aux messages d’erreur

Merci!

**Comment by brunto** [comment]
Bonjour,
Merci pour ce retour, les apostrophes sont gérées de façon différentes selon les systèmes.
Nous allons essayer de reproduire l'erreur afin d'apporter une solution.

**Comment by Plasmakil** [comment]
Bonjour,

Même problème pour moi. L'export depuis MacOS ne peut être importé ni depuis MacOS ni depuis Windows. V2.2.0.

Merci pour votre aide.

**Comment by tfaujour** [comment]
> Merci pour ce retour, les apostrophes sont gérées de façon différentes selon les systèmes.
> Nous allons essayer de reproduire l'erreur afin d'apporter une solution.

Vous pouvez essayer de copier/coller l’apostrophe suivante: ’

> L'export depuis MacOS ne peut être importé ni depuis MacOS ni depuis Windows. V2.2.0.

J’ai réussi à résoudre mon problème en modifiant manuellement le fichier `pia.json` et en supprimant les caractères problématiques. Pour détecter les caractères en question, j’ai utilisé la commande `jq . pia.json` (sous Linux) qui donne par exemple (dans le message d’erreur) "`line 1, column 310`".

**Comment by brunto** [comment]
Bonjour,
L'erreur est corrigée, le correctif sera disponible dans la version 2.3 qui va sortir dans pas longtemps.

**Comment by Plasmakil** [comment]
Très bonne nouvelle ! Merci.

**Comment by brunto** [comment]
Bonjour,
Nous allons faire une version intermédiaire 2.2.1 très prochainement qui corrigera ce problème.
