### ISSUE TITLE
Partage de la base de données entre utilisateurs

### ISSUE THREAD

**Issue by Roma49** [LINCnil/pia-app#61]
Nous utilisons le logiciel PIA sur poste de travail (version 2.2.0 sous environnement Windows), nous avons pour l'instant mis de côté la version web.
En revanche, les utilisateurs souhaiteraient pouvoir partager la même base de données pour éviter les exports/imports de fichiers (échanges de fichiers zip et/ou json) au cours du workflow de validation.
En standard, les données sont stockées en local sur le poste dans le répertoire C:\Users\Username\AppData\Roaming\PIA. Est-il possible de mutualiser le stockage sur un répertoire réseau, la base de données accepterait-elle ces accès concurrents et comment seraient-ils gérés ?

**Comment by brunto** [comment]
Bonjour,
Ce fonctionnement est tout à fait possible mais si deux personnes éditent un champ en même temps, c'est le dernier qui sauvegarde ce champ qui écrasera la donnée.
