### ISSUE TITLE
Perte données suite a execution vieille version

### ISSUE THREAD

**Issue by okin283** [LINCnil/pia-app#62]
Bonjour,
Un utilisateur avait la version 2.2 et une vieille version en 1.7.
Elle travaillait sur le 2.2 ... et un matin par erreur elle a relancé la 1.7 ... et la plus de données.

A priori la 1.7 a ecrasé toutes les données.
Y a t'il une copie effectuée ou est-ce complètement perdu?
Merci
Nicolas

**Comment by brunto** [comment]
Bonjour,

Et en relançant la 2.2 ensuite il n'y avait toujours pas de données ?
Cette personne travaille en mode client/serveur ou juste en local ?

**Comment by okin283** [comment]
Bonjour,
oui en relancant la 2.2 il n'y a plus rien.
Elle travail en local  ... et avait pas faire d'export pour sauvegarder...

J'ai reproduit sur mon poste:
- je créer un questionnaire en 1.7
- j'installe la version 2.2 et on retrouve bien le questionnaire.
- je reinstalle la 1.7 , je lance je n'ai plus rien.

Y a t'il espoir que lorsqu'on a relancé la 1.7, il ai laissé une copie des données quelque part?

**Comment by brunto** [comment]
Bonjour,
J'ai effectué des tests entre ces deux versions.
Effectivement si on rebascule sur l'ancienne version les données sont écrasées.
Malheureusement il n'est pas possible de récupérer les données sauf si vous aviez sauvegarder le disque dur de votre ordinateur avant de basculer sur l'ancienne version.
Veuillez nous excuser pour ce dysfonctionnement, nous vous encourageons à utiliser la fonction d'export afin de garder des sauvegardes de vos PIAS.
