### ISSUE TITLE
App starts with a blank window

### ISSUE THREAD

**Issue by muelli** [LINCnil/pia-app#71]
I am trying to make a Flatpak for this app and the app starts with a blank window:

![image](https://user-images.githubusercontent.com/322807/94479870-b61dcc00-01d5-11eb-87bf-fa0f86f2de74.png)

```
[📦 fr.cnil.piaapp ~]$ run.sh 
Gtk-Message: 21:58:00.902: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:58:00.902: Failed to load module "canberra-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

How can I further debug this behaviour?

FTR: The manifest is [here](https://github.com/muelli/flathub/commit/37cb4daaf045ccc0b2b6b72884bb3c0c169ab85d).

**Comment by brunto** [comment]
Hi @muelli 
Flatpak is pretty cool but we don't have been able to try it for now.
I can't provide you some help with this.
