### ISSUE TITLE
Network traffic to Github

### ISSUE THREAD

**Issue by optimizedconfusion** [LINCnil/pia-app#80]
Hello, using the Windows portable version we're seeing regular connections from pia.exe to Github. Could you provide more information about what this connection is for and what data is transferred during these sessions? Thank you.

**Comment by brunto** [comment]
Hello, when the application is launch, a call is made on Github to find the latest version number present in the file latest.yml if the application finds a higher version number you'll be prompt to download it.
Of course, no data are sent to Github.

**Comment by optimizedconfusion** [comment]
> Hello, when the application is launch, a call is made on Github to find the latest version number present in the file latest.yml if the application finds a higher version number you'll be prompt to download it.
> Of course, no data are sent to Github.

Thank you very much for your prompt response!
